In [44]:
print("hello")


hello


In [45]:
print("hello world")

hello world


In [46]:
from concurrent.futures import ProcessPoolExecutor
import time

def square_number(number):
    time.sleep(2)
    return f"Square: {number * number}"

numbers=[1,2,3,4,5,6,7,8,9,11,2,3,12,14]
if name=="main":

    with ProcessPoolExecutor(max_workers=3) as executor:
        results=executor.map(square_number,numbers)

    for result in results:
        print(result)

NameError: name 'name' is not defined

In [3]:
## Determine the ticket price based on age and whether the person is a student.
# Ticket pricing based on age and student status

# Take user input
age = int(input("Enter your age: "))
is_student = input("Are you a student? (yes/no): ").lower()

if age < 5:
    price = "Free"
elif age <= 12:
    price = "$10"
elif age <= 17:
    price = "$12" if is_student == 'yes' else "$15"
elif age <= 64:
    price = "$18" if is_student == 'yes' else "$25"
else:
    price = "$20"

print("Ticket Price:", price)



Ticket Price: $10


In [1]:
for i in range(5):
    print(i)

0
1
2
3
4


In [2]:
for i in range(1,10,2):
    print(i)
    

1
3
5
7
9


In [3]:
str = "krish naik"
for i in str:
    print(i)

k
r
i
s
h
 
n
a
i
k


In [ ]:
count = 0
while count < 5:
    print(count)
    count = count + 1


0
1
2
3
4


In [12]:
count = 0
while count < 10:
    if count % 2 == 0:
        print(count)
    count += 1
    
    

0
2
4
6
8


In [13]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


In [16]:
for i in range(3):
    for j in range(2):
        print(f"1:{i}and 2:{j}")

1:0and 2:0
1:0and 2:1
1:1and 2:0
1:1and 2:1
1:2and 2:0
1:2and 2:1


In [19]:
lst1 = [1, 2, 3, 4]
lst2 = ['a', 'b', 'c', 'd']
pair = [(i, j) for i in lst1 for j in lst2]
print(pair)

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd')]


In [20]:
lst1 = [1,2,3,4]
lst2 = ['a','b','c','d']
pair = [(i,j)for i in lst1 for j in lst2]
print(pair)

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd')]


In [21]:
lst = []
for x in range(10):
    lst.append(x**2)
    print(lst)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [22]:
square = [num**2 for num in range(10)]
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [20]:
n = 10
sum = 0
count = 1

while count <= n:
    sum += count
    count += 1

print(f"Sum of first ten numbers is{sum}" )

Sum of first ten numbers is55


In [21]:
for i in range(0,3):
    for j in range (5):
        print(f"i:{i}and j;{j}")

i:0and j;0
i:0and j;1
i:0and j;2
i:0and j;3
i:0and j;4
i:1and j;0
i:1and j;1
i:1and j;2
i:1and j;3
i:1and j;4
i:2and j;0
i:2and j;1
i:2and j;2
i:2and j;3
i:2and j;4


In [3]:
n=10
sum=0
count=0
while count <= n:
    sum += count 
    count += 1
print(f"Sum of first ten numbers is {sum}")


Sum of first ten numbers is 55


In [7]:
n=10
sum = 0
for i in range(11):
    sum =sum+i
    print({sum})


{0}
{1}
{3}
{6}
{10}
{15}
{21}
{28}
{36}
{45}
{55}


In [8]:
lst = []
print(type(lst))

<class 'list'>


In [9]:
numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers[1:8])

[2, 3, 4, 5, 6, 7, 8, 9, 10]


In [23]:
numbers = [1,2,3,4,5,6,7,8,9,10]
print(numbers[::-1])
print(numbers[::-2])
print(type(numbers))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 8, 6, 4, 2]
<class 'list'>


In [27]:
lst=[]
for x in range(10):
    lst.append(x**2)
    print(lst)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [31]:
{x**2 for x in range(10)}

{0, 1, 4, 9, 16, 25, 36, 49, 64, 81}

In [32]:
square = [ num**2 for num in range(10) ]
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
wods=["hello", "world", "python", "is", "great"]
lengths = 

In [1]:
from packages import maths
maths.addition(1, 2)

ModuleNotFoundError: No module named 'packages'

In [1]:
import array 
arr = array.array('i', [1, 2, 3, 4, 5])
print(arr)

array('i', [1, 2, 3, 4, 5])


In [2]:
from packages import maths
maths.addition(1, 2)

ModuleNotFoundError: No module named 'packages'

In [5]:
import math
print(math.sqrt(16))
print(math.pi)

4.0
3.141592653589793


In [8]:
import random
print(random.randint(1,10))
print(random.choice(['apple','banana','cherry','guava']))

3
guava


import os
print(os.getcwd())

In [9]:
import os 
print(os.getcwd())

c:\Users\b2hkr\OneDrive\Desktop\JN


In [10]:
os.mkdir('test_dir')

In [ ]:
import shutil
# The variable 'dst' is not defined. 
# If you want to create a symlink from 'source.txt' to 'destination.txt', you can use:
os.symlink(os.readlink('source.txt'), 'destination.txt')
shutil.copyfile('source.txt','destination.txt')

In [1]:
import json
data = {'name': 'Krishendu', 'age': 18}
json_str = json.dumps(data)
print(json_str)
print(type(json_str))
parsed_data= json.loads(json_str)
print(parsed_data)
print(type(parsed_data))

{"name": "Krishendu", "age": 18}
<class 'str'>
{'name': 'Krishendu', 'age': 18}
<class 'dict'>


In [4]:
import csv
with open('example.csv',mode='w',newline='')as file:
writer= csv.writer(file)
    writer.writerow(['Name', 'Age'])
    writer.writerow(['Krishendu', 18])
    

IndentationError: expected an indented block after 'with' statement on line 2 (1097619341.py, line 3)

In [2]:
from datetime import datetime,timedelta
now = datetime.now()
print(now)
yesterday = now - timedelta(days=1)
print(yesterday)


2025-07-09 12:53:35.277317
2025-07-08 12:53:35.277317


In [1]:
num = int(input("enter a number"))
if num%2 == 0 :
    print("even")
else:
    print("odd")

odd


In [6]:
year = int(input("enter a year"))
if (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0):
    print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

2004 is a leap year


In [ ]:
def calculator():
    print("select operation:")
    print("1 for addition(+)")
    print(" 2 for substraction")
    print("3 for multiplication(*)")
    print(" 4 for division")
    


In [29]:
def is_strong_password(password):
    """ this function checks if the password is strong or weak """
    password = input("enter a password")
    if len(password) < 8:
        return "weak password"
    if not any(char.isdigit() for char in password):
        return "weak password"
    if not any(char.islower() for char in password):
        return "weak password"
    if not any(char.isupper() for char in password):
        return "weak password"
    if not any(char in "!@#$%^&*()-_=+[]{}|;:,.<>?/" for char in password):
        return "weak password"
    else:
        return "the password is strong"

In [ ]:

def greet(name):
    return (f"Hello {name}")
    print(greet("Krish"))


In [ ]:
import math 
math.sqrt(16)



In [4]:

import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

# %%
import numpy as np    

# %%
random_array = np.random.randint(1, 101, size=(4, 4))
print("Original Array:")                        

# %%
import sqlite3

# %%
connection=sqlite3.connect('example.db')
connection

# %%
cursor = connection.cursor()

# %%
cursor.execute('''
               create Table If Not Exists employee(
               id Integer Primary Key,
               name Text Not Null,
               age Integer,
               department text
               )
               ''')
## Commit the changes
connection.commit()

# %%
cursor.execute('''
 Select * from employee
''')

# %%
cursor.execute('''
               insert into employee (id, name, age, department)
               values (1, 'Krish', 25, 'IT')
                ''')
cursor.execute('''
            insert into employee (id,name,age,department)
               values (2,'bob',25,'engineering')
               ''')
cursor.execute('''
            insert into employee (id,name,age,department)
               values (3,'alice',30,'HR')
               ''')
connection.commit()



# %%
cursor.execute('select * from employee')

row = cursor.fetchall()

for row in row:
    print(row)

# %%
cursor.execute('''
            UPDATE employee
               set age= 26
               where id=1
               ''')
connection.commit()

# %%
cursor.execute('select * from employee')

row = cursor.fetchall()

for row in row:
    print(row)

# %%
cursor.execute('''
DELETE FROM employee
WHERE name='bob'
''')
connection.commit()


# %% [markdown]
# 

# %%
cursor.execute('select * from employee')

row = cursor.fetchall()

for row in row:
    print(row)


Original array:
[[14 13  7  9  6]
 [20 20 13 15 11]
 [14 11 13 18 17]
 [18  2 12 20  5]
 [ 3 18 15 18  5]]
Modified array:
[[14 13  1  9  6]
 [20 20  1 15 11]
 [14 11  1 18 17]
 [18  2  1 20  5]
 [ 3 18  1 18  5]]
Original Array:
(1, 'Krish', 25, 'IT')
(2, 'bob', 25, 'engineering')
(3, 'alice', 30, 'HR')
(1, 'Krish', 26, 'IT')
(2, 'bob', 25, 'engineering')
(3, 'alice', 30, 'HR')
(1, 'Krish', 26, 'IT')
(3, 'alice', 30, 'HR')


In [ ]:
cursor.execute('''
               insert into employee (id, name, age, department)
               values (1, 'Krish', 25, 'IT')
                ''')
cursor.execute('''
            insert into employee (id,name,age,department)
               values (2,'bob',25,'engineering')
               ''')
cursor.execute('''
            insert into employee (id,name,age,department)
               values (3,'alice',30,'HR')
               ''')
connection.commit()


In [ ]:
lass Animal:
    def __init__(self, name, sound):
        self.name = name
        self.sound = sound

    def make_sound(self):
        print(f"{self.name} makes a sound: {self.sound}")

class Dog(Animal):
    def fetch(self):
        print(f"{self.name } is fetching the ball")

        
dog1 = Dog("Buddy", "Bark")
dog1.make_sound()

In [ ]:
class cat(Animal):
    
    def scratch(self):
        print(f"{self.name} is scratching the sofa")
    def make_sound(self):
        print(f"{self.name} makes a sound swiftly")

chor = cat("chor", "maw_maw")
chor.make_sound()
chor.scratch()

In [ ]:
# %%
class Student:
    def __init__(self, name):
        self.name = name

    def show(self):
        print("Name:", self.name)

s = Student("rahul")
s.show()
    

In [3]:
from math import *
print(sqrt(16))
print(pi)


from  import addition
addition(2,3)


from package import maths 
maths.addition(1,2)


from package.maths import addition
addition(1,2)


from packages import gand
gand.Addition(1, 2)

from packages.gand import Addition 
addition(1, 2)


SyntaxError: invalid syntax (2014726496.py, line 6)

In [5]:
mixed_tuple = (1, 2.5, 'hello', True, None,3.14)
print(mixed_tuple[5])

3.14
